class Cuestionario < ApplicationRecord
  validates :email, presence: true, format: { with: /\w+@\w+\.\w{2}/ }
  validates :edad, presence: true
  validates :sexo, presence: true
  validates :escolaridad, presence: true
  validates :pais, presence: true
  validates :ciudad, presence: true
  validates :localidad, presence: true
  validates :peso, presence: true
  validates :altura, presence: true
  validates :alimentacion_sana, presence: true
  validates :alimentacion_dana_ambiente, presence: true
  validates :persona_actividad, presence: true
  validates :actividad_fisica, presence: true
  validates :sobrepeso, presence: true
  validates :obesidad, presence: true
  validates :hipertension, presence: true
  validates :colesterol, presence: true
  validates :trigliceridos, presence: true
  validates :diabetes, presence: true
  validates :glucosa, presence: true
  validates :diabetes_familia, presence: true
  validates :dieta, presence: true
  validates :origen_vegetales, presence: true
  validates :origen_frutas, presence: true
  validates :origen_carne, presence: true
  validates :origen_leche, presence: true
  validates :origen_cereales, presence: true
  validates :frecuencia_res, presence: true
  validates :frecuencia_puerco, presence: true
  validates :frecuencia_borrego, presence: true
  validates :frecuencia_pollo, presence: true
  validates :frecuencia_salmon, presence: true
  validates :frecuencia_atun, presence: true
  validates :frecuencia_leche, presence: true
  validates :frecuencia_queso, presence: true
  validates :frecuencia_yogurt, presence: true
  validates :frecuencia_pescados_mariscos, presence: true
  validates :frecuencia_huevo, presence: true
  validates :frecuencia_vegetales, presence: true
  validates :cantidad_vegetales, presence: true
  validates :frecuencia_fruta, presence: true
  validates :cantidad_fruta, presence: true
  validates :frecuencia_arroz, presence: true
  validates :frecuencia_leguminosas, presence: true
  validates :frecuencia_avena, presence: true
  validates :frecuencia_amaranto, presence: true
  validates :frecuencia_tortillas, presence: true
  validates :insectos, presence: true
  validates :frecuencia_tamales, presence: true
  validates :frecuencia_atole, presence: true
  validates :frecuencia_sandwich, presence: true
  validates :frecuencia_tacos, presence: true
  validates :frecuencia_torta, presence: true
  validates :frecuencia_bolillo, presence: true
  validates :frecuencia_sopas, presence: true
  validates :frecuencia_jugos, presence: true
  validates :frecuencia_refrescos, presence: true
  validates :frecuencia_bebidas_energetizantes, presence: true
  validates :frecuencia_galletas, presence: true
  validates :frecuencia_embutidos, presence: true
  validates :frecuencia_pan, presence: true
  validates :frecuencia_frituras, presence: true
  validates :frecuencia_chocolates, presence: true
end
